### ISSUE TITLE
I can't install the package

### ISSUE THREAD

**Issue by gotroch** [nicolasbeauvais/flysystem-onedrive#4]
composer require nicolas-beauvais/flysystem-onedrive
                                                                           
  [InvalidArgumentException]                                                   
  Could not find a matching version of package nicolas-beauvais/flysystem-one  
  drive. Check the package spelling, your version constraint and that the pac  
  kage is available in a stability which matches your minimum-stability (stab  
  le).

**Comment by nicolasbeauvais** [comment]
Hello @gotroch,

Indeed the command should be :
```
composer require nicolasbeauvais/flysystem-onedrive
```

I'm updating the `Readme.md` file to fix this typo.

Thank you!
