### ISSUE TITLE
Error: Return value of OneDriveAdapter::listContents() must be of the type array, boolean returned

### ISSUE THREAD

**Issue by jozeflambrecht** [nicolasbeauvais/flysystem-onedrive#5]
When I run the spatie/laravel-backup script and choose OneDrive as disk, I get the following output and error:
```
Dumping database xkxr******...
Determining files to backup...
Zipping 1 files...
Created zip containing 1 files. Size is 968.09 KB
Copying zip to disk named onedrive...
Successfully copied zip to disk named onedrive.

In OneDriveAdapter.php line 237:

  Return value of NicolasBeauvais\FlysystemOneDrive\OneDriveAdapter::listCont
  ents() must be of the type array, boolean returned
```
When I look to my OneDrive, I do not see the backup of my database.
These are my permissions:

![image](https://user-images.githubusercontent.com/11506957/45334004-d921a880-b546-11e8-96c9-2562c0429f14.png)

What could be the problem? Thank you for making these packages!

**Comment by jozeflambrecht** [comment]
https://stackoverflow.com/questions/48667036/create-app-folder-in-one-drive-for-business-privileges?rq=1

I have a OneDrive for Business account and apparently it does not support this ...

**Comment by nicolasbeauvais** [comment]
Hello @jozeflambrecht,

This issue has already been reported to the one drive team a year ago but apparently, it has not been fixed yet: https://github.com/OneDrive/onedrive-api-docs/issues/682
