### ISSUE TITLE
error: OneDriveAdapter::listContents() on consumer account

### ISSUE THREAD

**Issue by fabianobn** [nicolasbeauvais/flysystem-onedrive#6]
Hello, I is user consumer in onedrive and I receive this error: 

[Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Return value of NicolasBeauvais\FlysystemOneDrive\OneDriveAdapter::listContents() must be of the type array
  , boolean returned

**Comment by cvaize** [comment]
Hello, I am also getting this error and would like to know the solution.

**Comment by nicolasbeauvais** [comment]
Hello @fabianobn, @cvaize,

I do not maintain this library anymore as keeping up with the API change take too much time and Microsoft (in my opinion) doesn't do much to help us (cf. https://github.com/OneDrive/onedrive-api-docs/issues/682).

You can probably fork and update this repository to make a more up-to-date driver for flysystem like I did 2 years ago or find a working implementation on another repository.

Good luck!
